format = """
(#a0a9cb)$username$hostname|(white)$directory$git_branch$c$rust$dotnet$python$nodejs$lua$php$golang
(#a0a9cb)$character"""

add_newline = false
command_timeout = 1000

[username]
style_user = "#a0a9cb"
format = "[ ](fg:white)[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](white)[on](#a0a9cb) 󰌢  [$hostname](#a0a9cb) '
trim_at = '.companyname.com'
disabled = false

[character]
success_symbol = "[❯](white)"

[directory]
style = "fg:white"
format = ' 󰉋 [$path]($style) '
truncation_length = 0
truncate_to_repo = false
home_symbol = "Home"

[directory.substitutions]
"Documents" = "󰈙 Documents"
"ASCII" = " ASCII"
"Downloads" = " Downloads"
"Music" = " Music"
"Pictures" = " Pictures"
"Videos" = " Videos"
"Movies" = "󰿎 Movies"
"Coding" = "󱃖 Coding"
"Library" = " Library"
"Blender" = "󰂫 Blender"
"Fonts" = " Fonts"
"Repos" = " Repos"
"Wallpapers" = " Wallpapers"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '|[[   $symbol $branch ](fg:#769ff0)]($style)'

[c]
symbol = ""
style = "bg:#394260"
detect_extensions = ["c", "h", "cc", "cpp", "hh", "hpp"]
format = '|[[ $symbol $name $version ](fg:#5597d2)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '|[[ $symbol ($version) ](fg:#9ece6a)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '|[[ $symbol ($version) ](fg:#ff6247)]($style)'

[dotnet]
symbol = " "
style = "bg:#212736"
heuristic = false
format = '|[[ $symbol ($version) ](fg:#512ad5)]($style)'

[python]
symbol = ''
style = "bg:#212736"
format = '|[[ $symbol ($version) ](fg:#e0af68)]($style)'

[lua]
symbol = "󰢱"
style = "bg:#212736"
format = '|[[ $symbol ($version) ](fg:#7aa2f7)]($style)'

[golang]
symbol = "󰟓"
style = "bg:#212736"
format = '|[[ $symbol ($version) ](fg:#2ac3de)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '|[[ $symbol ($version) ](fg:#565f89)]($style)'
