gui:

  nerdFontsVersion: "3"

  spinner:
    # The frames of the spinner animation.
    frames:
      - '⠟'
      - '⠯'
      - '⠷'
      - '⠾'
      - '⠽'
      - '⠻'

    # The "speed" of the spinner in milliseconds.
    rate: 50
